Repository rymen80/issueManager, pull requests merged in 2020-11, with the labels that each got.

#6 add new db folder to contain schema definition and seed data
  db/schema.sql
Labels: Project Task

#18 Lindseysbranch
  client/package-lock.json
  client/src/App.jsx
  client/src/images/issUse.png
  client/src/images/issUseLogo.png
  client/src/pages/Viewer/ViewerViews/SignIn.jsx
  client/src/pages/common/components/StatusCard.jsx
  client/src/styles/App.css
Labels: enhancement

#19 change urer orm queries and update connection.js with a console.log message for debugging
  config/connection.js
  model/userQueries.js
Labels: Project Task

#20 add Admin button to signin page and also extract the copyright component out of sign in page
  Utils/getHashedPassword.js
  client/src/pages/Viewer/ViewerViews/SignIn.jsx
  client/src/pages/common/components/LoginPagesCopyright.jsx
  config/connection.js
  controllers/issuesContoller.js
  model/issuesOrm.js
  model/issuesQueries.js
  package-lock.json
  package.json
  routes/apiRoutes/index.js
  routes/apiRoutes/issuesRoutes/index.js
Labels: Project Task

#27 Ryan m
  client/src/pages/common/components/MenuDropDown.jsx
  routes/apiRoutes/issuesRoutes/index.js
Labels: enhancement

#30 remove willstestfile
  willstestfile
Labels: invalid

#31 add swagger definition to the index.js
  index.js
  package-lock.json
  package.json
Labels: enhancement

#28 add Footer component and add navbar2 and add JSON dependencies
  client/package-lock.json
  client/package.json
  client/src/pages/common/components/willTools/Box.jsx
  client/src/pages/common/components/willTools/Footer.jsx
  client/src/pages/common/components/willTools/Navbars/AdminNavbarLinks.js
  client/src/pages/common/components/willTools/Navbars/Button.js
  client/src/pages/common/components/willTools/Navbars/CustomInput.js
  client/src/pages/common/components/willTools/Navbars/Navbar2.js
  client/src/pages/common/components/willTools/Navbars/RTLNavbarLinks.js
  client/src/pages/common/components/willTools/Navbars/buttonStyle.js
  client/src/pages/common/components/willTools/Navbars/customInputStyle.js
  client/src/pages/common/components/willTools/Navbars/dropdownStyle.js
  client/src/pages/common/components/willTools/Navbars/headerLinksStyle.js
  client/src/pages/common/components/willTools/Navbars/headerStyle.js
  client/src/pages/common/components/willTools/Navbars/rtlHeaderLinksStyle.js
  client/src/pages/common/components/willTools/footerStyle.js
  client/src/pages/common/components/willTools/material-dashboard-react.js
Labels: enhancement

#32 add swagger definitions and documentation comments
  routes/apiRoutes/index.js
  routes/apiRoutes/issuesRoutes/index.js
  routes/authRoutes/index.js
  routes/index.js
Labels: documentation

#33 remove unnecessary routes folder and add blank route files
  index.js
  routes/apiRoutes/commentsRoutes.js
  routes/apiRoutes/issuesRoutes.js
  routes/apiRoutes/labelsRoutes.js
  routes/apiRoutes/projectRoutes.js
  routes/apiRoutes/userRoutes.js
Labels: Project Task

#34 add projectOrm and projectQueries
  model/projectOrm.js
  model/projectQueries.js
Labels: Project Task

#35 add end to end project route including controller, routes, orm and q…
  controllers/projectController.js
  index.js
  model/projectOrm.js
  model/projectQueries.js
  routes/apiRoutes/index.js
  routes/apiRoutes/projectRoutes.js
  routes/index.js
Labels: Project Task

#41 complete user route including routes, controller,orm and queries
  controllers/usersController.js
  model/userOrm.js
  model/userQueries.js
  routes/apiRoutes/userRoutes.js
Labels: Project Task

#42 cleanse and documentation
  controllers/authController.js
  routes/authRoutes/index.js
  services/passport.js
Labels: Project Task

#43 update index.js for swagger
  index.js
Labels: Project Task

#44 complete issue post
  controllers/issuesContoller.js
  model/issuesOrm.js
  routes/apiRoutes/index.js
  routes/apiRoutes/issuesRoutes.js
  routes/apiRoutes/projectRoutes.js
Labels: Project Task

#45 update issue Queries
  model/issuesQueries.js
Labels: Project Task

#46 create navbar user, project selector, admin transfer, report bug button components
  client/src/pages/common/components/AdminTransfer.jsx
  client/src/pages/common/components/NavbarUser.jsx
  client/src/pages/common/components/ProjectSelector.jsx
  client/src/pages/common/components/ReportIssueButton.jsx
  client/src/pages/common/components/willTools/Footer.jsx
Labels: enhancement

#47 remove unwanted code
  routes/authRoutes/index.js
Labels: bug

#48 make signin defualt route and change token to 'userauth' to store in …
  client/src/App.jsx
  client/src/pages/Viewer/ViewerViews/SignIn.jsx
Labels: bug

#55 remove duplicate imports
  client/src/App.jsx
Labels: bug

#67 Add styling for create Issue form, fix userPage redux
  client/src/pages/User/index.jsx
  client/src/pages/common/components/CreateIssue.jsx
  client/src/redux/index.js
Labels: enhancement

#69 correct the NODE_DB_NV to NODE_DB_ENV
  config/connection.js
Labels: bug

#70 rename UserReducer.jsx to UserReducer.js
  client/src/pages/User/UserReducer.js
Labels: enhancement

#71 update User reducer and authcontroller to get username and id make ch…
  client/src/pages/User/SignIn.jsx
  client/src/pages/User/UserReducer.js
  client/src/redux/index.js
  controllers/authController.js
Labels: enhancement

#72 project button now displaying users projects
  client/src/pages/common/components/ProjectSelector.jsx
  client/src/pages/common/components/StatusCard.jsx
Labels: enhancement

#73 Admin Page Build
  client/src/pages/Admin/AdminCards.jsx
  client/src/pages/Admin/AdminPage.jsx
  client/src/pages/Admin/AdminSignIn.jsx
  client/src/pages/Admin/adminReducer.js
  client/src/pages/common/components/AdminNavbar.jsx
  client/src/pages/common/components/index.jsx
Labels: enhancement

#74 add swagger button
  client/src/images/api.png
  client/src/images/swagger.png
  client/src/pages/Admin/AdminSignIn.jsx
  client/src/pages/common/components/AdminNavbar.jsx
  client/src/pages/common/components/LoginPagesCopyright.jsx
Labels: enhancement

#76 add viewAllProjects data Grid
  client/package-lock.json
  client/package.json
  client/src/pages/Admin/AdminCards.jsx
  client/src/pages/Admin/AdminPage.jsx
  client/src/pages/Admin/ViewAllProjects.jsx
  client/src/pages/Admin/adminPageReducer.js
  client/src/pages/Admin/index.jsx
  client/src/pages/common/components/AdminNavbar.jsx
  client/src/redux/index.js
Labels: enhancement

#82 Issue item
  client/src/pages/common/components/Footer2.jsx
  client/src/pages/common/components/IssueItem.jsx
  client/src/pages/common/components/StyledButton.jsx
  client/src/pages/common/components/willTools/Box.jsx
  client/src/pages/common/components/willTools/Navbars/AdminNavbarLinks.js
  client/src/pages/common/components/willTools/Navbars/Button.js
  client/src/pages/common/components/willTools/Navbars/CustomInput.js
  client/src/pages/common/components/willTools/Navbars/Navbar2.js
  client/src/pages/common/components/willTools/Navbars/RTLNavbarLinks.js
  client/src/pages/common/components/willTools/Navbars/buttonStyle.js
  client/src/pages/common/components/willTools/Navbars/customInputStyle.js
  client/src/pages/common/components/willTools/Navbars/dropdownStyle.js
  client/src/pages/common/components/willTools/Navbars/headerLinksStyle.js
  client/src/pages/common/components/willTools/Navbars/headerStyle.js
  client/src/pages/common/components/willTools/Navbars/rtlHeaderLinksStyle.js
  client/src/pages/common/components/willTools/footerStyle.js
  client/src/pages/common/components/willTools/material-dashboard-react.js
Labels: Project Task

#83 removed clutter component
  client/src/pages/common/components/willTools/Footer.jsx
Labels: Cleanup Task

#84 resolve Linting warnings
  client/src/App.jsx
  client/src/pages/Admin/AdminCards.jsx
  client/src/pages/Admin/AdminPage.jsx
  client/src/pages/Admin/AdminSignIn.jsx
Labels: Cleanup Task

#87 make get users call as non admin
  controllers/projectController.js
  controllers/usersController.js
Labels: enhancement

#89 final footer
  client/src/pages/common/components/Footer.jsx
  client/src/pages/common/components/Footer2.jsx
Labels: enhancement

#90 documentation and final changes
  client/src/images/issUseBannerTransparent.png
  client/src/pages/Admin/AdminPage.jsx
  client/src/pages/Admin/AdminSignIn.jsx
  client/src/pages/Admin/CreateProject.jsx
  client/src/pages/Admin/ViewAllProjects.jsx
  client/src/pages/Admin/adminPageReducer.js
  client/src/pages/Admin/index.jsx
  client/src/pages/Admin/views/AdminCards.jsx
  client/src/pages/Admin/views/ViewAllProjects.jsx
  client/src/pages/Admin/views/index.jsx
  client/src/pages/User/UserView.jsx
  client/src/pages/common/components/AdminNavbar.jsx
  client/src/pages/common/components/UserProfile.jsx
  client/src/pages/common/components/index.jsx
  controllers/usersController.js
  routes/apiRoutes/userRoutes.js
Labels: Cleanup Task

#98 add selectedProject state
  client/src/pages/User/UserPageReducer.js
Labels: enhancement

#99 change footer to always display at bottom
  client/src/pages/common/components/Footer.jsx
Labels: enhancement

#100 resolve the Footer reference
  client/src/pages/User/UserPage.jsx
Labels: bug

#101 make redux changes to navbaruser, projectSelectorNew and delete unwan…
  client/src/pages/User/UserController.jsx
  client/src/pages/User/UserView.jsx
  client/src/pages/User/index.jsx
  client/src/pages/common/components/Navbar.jsx
  client/src/pages/common/components/NavbarUser.jsx
  client/src/pages/common/components/ProjectSelector.jsx
  client/src/pages/common/components/ProjectSelectorNew.jsx
  client/src/pages/common/components/ReportIssueButton.jsx
  client/src/pages/common/components/index.jsx
Labels: Cleanup Task, enhancement

#102 update userpage reducer, add functionality to userPage,update project…
  client/src/pages/User/UserPage.jsx
  client/src/pages/User/UserPageReducer.js
  client/src/pages/User/UserView.jsx
  client/src/pages/User/Views/StatusCardsView.jsx
  client/src/pages/common/components/ProjectSelectorNew.jsx
  client/src/pages/common/components/StatusCard.jsx
Labels: enhancement

#103 bug fix : event.persist() call in projectSelectorNew onChange event
  client/src/pages/User/Views/StatusCardsView.jsx
  client/src/pages/common/components/ProjectSelectorNew.jsx
  client/src/pages/common/components/StatusCard.jsx
Labels: bug

#104 resolve routing issues
  client/src/pages/User/UserPage.jsx
  client/src/pages/common/components/CreateIssue.jsx
  client/src/pages/common/components/NavbarUser.jsx
Labels: bug

#111 finish readMe add contributors images
  images/Abhi.png
  images/Chris.png
  images/Lindsey.jpeg
  images/Will.png
  images/ryan.jpeg
  readme.md
Labels: enhancement

#113 update admin card and work on add project/edit project
  client/src/pages/Admin/AdminPage.jsx
  client/src/pages/Admin/adminPageReducer.js
  client/src/pages/Admin/views/AdminCards.jsx
  client/src/pages/Admin/views/CreateProject.jsx
  client/src/pages/Admin/views/CreateUserView.jsx
  client/src/pages/Admin/views/ViewAllProjects.jsx
  client/src/pages/Admin/views/index.jsx
Labels: enhancement

#114 remove absolute position of footer
  client/src/pages/common/components/Footer.jsx
Labels: enhancement

#115 make update project work
  client/src/pages/Admin/views/ViewAllProjects.jsx
Labels: enhancement

#116 demoable UserProfile.jsx fix Back Button
  client/src/pages/common/components/UserProfile.jsx
Labels: documentation

#117 add demoable createUserView
  client/src/pages/Admin/AdminPage.jsx
  client/src/pages/Admin/views/AdminCards.jsx
  client/src/pages/Admin/views/CreateUserView.jsx
  client/src/pages/Admin/views/index.jsx
Labels: enhancement

#118 make partial checkin for viewAllUsers.jsx
  client/src/pages/Admin/AdminPage.jsx
  client/src/pages/Admin/views/AdminCards.jsx
  client/src/pages/Admin/views/ViewAllUsers.jsx
  client/src/pages/Admin/views/index.jsx
  model/userQueries.js
Labels: enhancement

#120 complete ViewAllUser.jsx
  client/src/pages/Admin/adminPageReducer.js
  client/src/pages/Admin/views/ViewAllUsers.jsx
Labels: enhancement

#121 cleanse and update
  client/src/pages/User/UserPage.jsx
  client/src/pages/common/components/Footer.jsx
  client/src/pages/common/components/StatusCard.jsx
Labels: Cleanup Task

#122 fix title
  client/src/pages/User/Views/StatusCardsView.jsx
Labels: bug

#123 style and resolve onDrawerClose for menu click
  client/src/pages/common/components/NavbarUser.jsx
  client/src/pages/common/components/StatusCard.jsx
Labels: bug

#124 resolve project selector bug and change look and feel of status card
  client/src/pages/common/components/ProjectSelectorNew.jsx
  client/src/pages/common/components/StatusCard.jsx
Labels: bug

#125 resolve signout issue and linter warnings
  client/src/pages/User/SignIn.jsx
  client/src/pages/common/components/NavbarUser.jsx
  client/src/pages/common/components/StatusCard.jsx
Labels: Cleanup Task, bug

#126 change the fetch project axios request
  client/src/pages/common/components/CreateIssue.jsx
  client/src/pages/common/components/NavbarUser.jsx
Labels: bug

#128 get the issue grids working
  client/src/pages/User/UserPage.jsx
  client/src/pages/User/UserPageReducer.js
  client/src/pages/User/Views/issueDetailViewNew.jsx
  client/src/pages/common/components/IssueGridWithEditForm.jsx
  client/src/pages/common/components/NavbarUser.jsx
Labels: enhancement

#131 Add sqls for creating schema, function, views and stored procs
  db/getprojectkey_function.sql
  db/issue_view.sql
  db/schema.sql
  db/storedprocs.sql
Labels: Project Task
